
<?php 
$servername = "localhost"; 
$username = "root"; 
$password = "";
$dbname = "Bank-data-management"; 
  
// Create connection 
$conn = mysqli_connect( $servername, $username, $password, $dbname ); 
  
// Check connection 
if ( !$conn ) { 
    die("Connection failed: " . mysqli_connect_error()); 
} 

$sql="INSERT INTO `AddressLocality` VALUES ('1','East Roderick', now()),
('2','Lake Donavon', now()),
('3','South Melissaborough', now()),
('4','Hettingermouth', now()),
('5','South Claudiachester', now()),
('6','Ziemeshire', now()),
('7','Bahringermouth', now()),
('8','North Grant', now()),
('9','Cobymouth', now()),
('10','Langworthtown', now()),
('11','West Colt', now()),
('12','Ziemefurt', now()),
('13','New Harley', now()),
('14','West Romainemouth', now()),
('15','Port Maxwellland', now()),
('16','Emelieburgh', now()),
('17','Evalynville', now()),
('18','Teaganstad', now()),
('19','Rebamouth', now()),
('20','Lake Lurlinechester', now()),
('21','Lake Orrinbury', now()),
('22','Lanceport', now()),
('23','South Mac', now()),
('24','North Margeton', now()),
('25','Elyseland', now()),
('26','East Adrian', now()),
('27','Othahaven', now()),
('28','South Jadentown', now()),
('29','Lavernastad', now()),
('30','Port Cullenmouth', now()),
('31','East Andreanne', now()),
('32','Claybury', now()),
('33','Lake Christymouth', now()),
('34','New Nakia', now()),
('35','Runteland', now()),
('36','Herzoghaven', now()),
('37','Oriestad', now()),
('38','Port Prince', now()),
('39','Jazlynmouth', now()),
('40','West Isabellside', now()),
('41','Thompsontown', now()),
('42','Darioview', now()),
('43','Lake Santino', now()),
('44','Port Noblebury', now()),
('45','Leilaniville', now()),
('46','Bednarland', now()),
('47','Michelleburgh', now()),
('48','North Claudieburgh', now()),
('49','Port Alfonso', now()),
('50','Kaleyburgh', now()),
('51','Huelview', now()),
('52','Lake Ken', now()),
('53','West Aurelie', now()),
('54','New Marcellefort', now()),
('55','Lake Misael', now()),
('56','South Carolynville', now()),
('57','West Lylafurt', now()),
('58','East Lydia', now()),
('59','East Ignaciotown', now()),
('60','East Naomimouth', now()),
('61','Wellingtonton', now()),
('62','Schustertown', now()),
('63','New Marilyne', now()),
('64','Satterfieldtown', now()),
('65','East Jazmyn', now()),
('66','Patrickfort', now()),
('67','Colehaven', now()),
('68','Runtechester', now()),
('69','Reichelfort', now()),
('70','New Modesta', now()),
('71','New Dorcasmouth', now()),
('72','Littleburgh', now()),
('73','West Melissa', now()),
('74','Yesseniashire', now()),
('75','Port Stacey', now()),
('76','Chanelleburgh', now()),
('77','West Kristopher', now()),
('78','Kayaberg', now()),
('79','New Casimirport', now()),
('80','Priceshire', now()),
('81','Enachester', now()),
('82','Gerardview', now()),
('83','Gleasonfurt', now()),
('84','Marshallfort', now()),
('85','Mayburgh', now()),
('86','North Kallie', now()),
('87','Port Colestad', now()),
('88','Effertzchester', now()),
('89','North Kiley', now()),
('90','Lafayettefurt', now()),
('91','Botsfordstad', now()),
('92','Kochville', now()),
('93','South Danielle', now()),
('94','Lake Brandomouth', now()),
('95','Hegmanntown', now()),
('96','Powlowskichester', now()),
('97','West Winonatown', now()),
('98','McClureberg', now()),
('99','West Moises', now()),
('100','Port Enochberg', now()),
('101','Collinsmouth', now()),
('102','East Lawrence', now()),
('103','Kerlukestad', now()),
('104','South Jovany', now()),
('105','Kiehnmouth', now()),
('106','Rogahnborough', now()),
('107','Mullermouth', now()),
('108','South Arnulfochester', now()),
('109','Lake Joliehaven', now()),
('110','Kylatown', now()),
('111','Thoraview', now()),
('112','Hudsonberg', now()),
('113','Leahaven', now()),
('114','Marcelland', now()),
('115','South Aniyah', now()),
('116','North Aniya', now()),
('117','Blazeburgh', now()),
('118','Bergeport', now()),
('119','Abbottchester', now()),
('120','Baileystad', now()),
('121','Lubowitzmouth', now()),
('122','North Marjory', now()),
('123','Kirlinmouth', now()),
('124','Lefflerbury', now()),
('125','Kyleeland', now()),
('126','East Rhettton', now()),
('127','East Bethel', now()),
('128','Sipesfort', now()),
('129','Baumbachstad', now()),
('130','Alexandroborough', now()),
('131','Baileyview', now()),
('132','Oswaldhaven', now()),
('133','Eichmannfurt', now()),
('134','Lake Jennieland', now()),
('135','Hilmachester', now()),
('136','Lynchburgh', now()),
('137','Trinityberg', now()),
('138','Laurynberg', now()),
('139','South Haskellshire', now()),
('140','East Doyle', now()),
('141','Jerdestad', now()),
('142','East Harmonfurt', now()),
('143','Connborough', now()),
('144','Huelsport', now()),
('145','Alfordbury', now()),
('146','West Breanamouth', now()),
('147','West Emeliafort', now()),
('148','South Yesenia', now()),
('149','Juanitamouth', now()),
('150','Lake Eli', now()),
('151','Russelberg', now()),
('152','West Tomshire', now()),
('153','Mannhaven', now()),
('154','Muhammadland', now()),
('155','Jonesfurt', now()),
('156','Schuppeland', now()),
('157','West Ivoryside', now()),
('158','Torphybury', now()),
('159','Lake Lorineshire', now()),
('160','Schimmelhaven', now()),
('161','East America', now()),
('162','West Ottilieborough', now()),
('163','North Aimee', now()),
('164','East Colten', now()),
('165','Harrisbury', now()),
('166','Cormierfort', now()),
('167','North Sybleville', now()),
('168','Lucasmouth', now()),
('169','Charleyburgh', now()),
('170','Macejkovicberg', now()),
('171','East Tatyanaton', now()),
('172','Bernicemouth', now()),
('173','Lake Maciberg', now()),
('174','Romagueraberg', now()),
('175','East Sageburgh', now()),
('176','North Waino', now()),
('177','Claudville', now()),
('178','New Shannyfurt', now()),
('179','Jessieland', now()),
('180','Lake Christina', now()),
('181','West Harley', now()),
('182','Yoststad', now()),
('183','Lake Cindy', now()),
('184','Satterfieldview', now()),
('185','North Victorland', now()),
('186','Lake Kamryn', now()),
('187','Port Darien', now()),
('188','West Zackaryfort', now()),
('189','Nealport', now()),
('190','Gorczanyburgh', now()),
('191','Port Gerdaland', now()),
('192','South Elliottshire', now()),
('193','Adeleburgh', now()),
('194','Hesselshire', now()),
('195','Hughmouth', now()),
('196','Dayanaville', now()),
('197','Rutherfordstad', now()),
('198','Kiehnfurt', now()),
('199','West Roxane', now()),
('200','Port Philip', now()),
('201','Jakeshire', now()),
('202','North Mckayla', now()),
('203','Ephraimmouth', now()),
('204','West Geraldine', now()),
('205','West Torey', now()),
('206','Lake Mckenna', now()),
('207','East Collinton', now()),
('208','South Assuntatown', now()),
('209','Lake Katrinastad', now()),
('210','New Charlieborough', now()),
('211','Gutkowskiborough', now()),
('212','Cronafurt', now()),
('213','North Edmundside', now()),
('214','West Marion', now()),
('215','East Lyric', now()),
('216','South Porter', now()),
('217','Adamshire', now()),
('218','Lake Cyrusberg', now()),
('219','West Florence', now()),
('220','Port Novaport', now()),
('221','Dachville', now()),
('222','Ziemetown', now()),
('223','Port Leonardchester', now()),
('224','Deechester', now()),
('225','New Anibal', now()),
('226','Giovannyborough', now()),
('227','East Hollie', now()),
('228','West Pauline', now()),
('229','Lake Katelynport', now()),
('230','Baileyborough', now()),
('231','New Laurianeland', now()),
('232','Kassandratown', now()),
('233','Walkerberg', now()),
('234','East Frank', now()),
('235','Port Maurice', now()),
('236','Rosinamouth', now()),
('237','Dominicview', now()),
('238','South Maryammouth', now()),
('239','Susannaland', now()),
('240','New Hardybury', now()),
('241','East Lauretta', now()),
('242','Mayrashire', now()),
('243','Strackeshire', now()),
('244','Delilahfurt', now()),
('245','Jacobsonview', now()),
('246','West Nayeli', now()),
('247','Lake Darienfurt', now()),
('248','Marilouburgh', now()),
('249','Marisaberg', now()),
('250','Taureanchester', now()),
('251','East Kacimouth', now()),
('252','Lake Yoshikoborough', now()),
('253','Port Zackaryhaven', now()),
('254','Ullrichmouth', now()),
('255','Gulgowskitown', now()),
('256','South Estelland', now()),
('257','Lake Jamiemouth', now()),
('258','New Arnold', now()),
('259','Port Calliefort', now()),
('260','Jacobsside', now()),
('261','Friesenbury', now()),
('262','West Dannieville', now()),
('263','Klingberg', now()),
('264','Port Leila', now()),
('265','Sistermouth', now()),
('266','New Freeman', now()),
('267','Furmanmouth', now()),
('268','Lake Yvonne', now()),
('269','South Roderickbury', now()),
('270','Murlview', now()),
('271','New Liliane', now()),
('272','Hirtheberg', now()),
('273','Xanderstad', now()),
('274','Kaydenborough', now()),
('275','Hermanmouth', now()),
('276','East Clementinaburgh', now()),
('277','New Tyresechester', now()),
('278','Arifort', now()),
('279','Port Tysonfort', now()),
('280','Roryfurt', now()),
('281','Sarahmouth', now()),
('282','West Madgestad', now()),
('283','Port Ellie', now()),
('284','East Alia', now()),
('285','Lake Ona', now()),
('286','Marielleport', now()),
('287','West Ebbaside', now()),
('288','New Frida', now()),
('289','South Quincymouth', now()),
('290','Juddmouth', now()),
('291','Port Jordon', now()),
('292','Dorisfort', now()),
('293','North Anthonychester', now()),
('294','North Deangelo', now()),
('295','New Eliezer', now()),
('296','Russelhaven', now()),
('297','East Justuston', now()),
('298','Considineton', now()),
('299','Port Zackery', now()),
('300','Geofurt', now()),
('301','Mohrfort', now()),
('302','New Nasir', now()),
('303','North Aryannashire', now()),
('304','Reillymouth', now()),
('305','West Euniceport', now()),
('306','East Ruthe', now()),
('307','Vivienchester', now()),
('308','West Brayan', now()),
('309','North Lindsayberg', now()),
('310','West Katlynn', now()),
('311','West Charleyside', now()),
('312','Willyville', now()),
('313','Estellview', now()),
('314','Port Guillermo', now()),
('315','Tatyanaborough', now()),
('316','Lake Afton', now()),
('317','Port Corbin', now()),
('318','Kayleeshire', now()),
('319','West Kirk', now()),
('320','Brandtside', now()),
('321','Lake Felicitatown', now()),
('322','Hyattmouth', now()),
('323','North Giovaniton', now()),
('324','Port Serenity', now()),
('325','Abshiremouth', now()),
('326','North Terrillhaven', now()),
('327','Stiedemannfort', now()),
('328','Felicityside', now()),
('329','Dallasstad', now()),
('330','Port Yasmineville', now()),
('331','Lillianside', now()),
('332','Jaquelinfort', now()),
('333','Marilynemouth', now()),
('334','Hilpertfort', now()),
('335','New Rivershire', now()),
('336','Port Emilfort', now()),
('337','Emmymouth', now()),
('338','East Braulioville', now()),
('339','Freedaton', now()),
('340','North Rosettafurt', now()),
('341','Hackettbury', now()),
('342','East Haleigh', now()),
('343','New Verner', now()),
('344','Jordanehaven', now()),
('345','Port Nickstad', now()),
('346','Bayermouth', now()),
('347','Port Arnoshire', now()),
('348','South Guiseppebury', now()),
('349','Kubstad', now()),
('350','Abernathyhaven', now()),
('351','Steuberport', now()),
('352','New Maxiechester', now()),
('353','Ruthieview', now()),
('354','Robelborough', now()),
('355','Vladimirstad', now()),
('356','Port Breanaburgh', now()),
('357','West Bennystad', now()),
('358','Flatleyville', now()),
('359','Port Deliaberg', now()),
('360','Tyreekton', now()),
('361','Lindgrenstad', now()),
('362','East Laurenchester', now()),
('363','Port Samanthashire', now()),
('364','Hannamouth', now()),
('365','Gregberg', now()),
('366','Lake Fannieberg', now()),
('367','Loriville', now()),
('368','Lake Axelshire', now()),
('369','Port Rosaleeside', now()),
('370','Feilberg', now()),
('371','Port Destiney', now()),
('372','Connshire', now()),
('373','West Camylle', now()),
('374','Stammville', now()),
('375','West Maybell', now()),
('376','Rebekaport', now()),
('377','Brookside', now()),
('378','Aminafort', now()),
('379','West Calebstad', now()),
('380','Willmsberg', now()),
('381','Lake Rosalind', now()),
('382','Bennettstad', now()),
('383','Leschfort', now()),
('384','Immanuelview', now()),
('385','New Beulahberg', now()),
('386','East Arabury', now()),
('387','South Janessa', now()),
('388','Armstrongview', now()),
('389','Travonberg', now()),
('390','New Osbaldobury', now()),
('391','Howeville', now()),
('392','East Bufordstad', now()),
('393','Port Casimirstad', now()),
('394','Jessikaton', now()),
('395','Lilyville', now()),
('396','Jonathontown', now()),
('397','South Mariahbury', now()),
('398','Jazlynborough', now()),
('399','Treutelshire', now()),
('400','Hansenside', now()),
('401','Stonehaven', now()),
('402','Harberfurt', now()),
('403','Fernstad', now()),
('404','Stiedemannshire', now()),
('405','Lubowitzside', now()),
('406','South Pattie', now()),
('407','Maximusberg', now()),
('408','West Jerad', now()),
('409','Port Edd', now()),
('410','Port Avafurt', now()),
('411','Richardchester', now()),
('412','Selinaton', now()),
('413','New Nicklaus', now()),
('414','Jarenshire', now()),
('415','North Dwight', now()),
('416','East Alverta', now()),
('417','Lake Angelfort', now()),
('418','Jerelport', now()),
('419','Carissaview', now()),
('420','West Keithview', now()),
('421','Jazlynberg', now()),
('422','West Lawson', now()),
('423','East Gustfurt', now()),
('424','Gorczanystad', now()),
('425','Inesberg', now()),
('426','West Tyreseview', now()),
('427','Serenaborough', now()),
('428','Reicheltown', now()),
('429','Victorview', now()),
('430','Estrellastad', now()),
('431','Branttown', now()),
('432','West Geraldhaven', now()),
('433','Jonesburgh', now()),
('434','West Laverne', now()),
('435','Lake Demarco', now()),
('436','Schneiderside', now()),
('437','Lilianabury', now()),
('438','Eloisachester', now()),
('439','Williamsonbury', now()),
('440','Port Alexa', now()),
('441','Kaseyfurt', now()),
('442','Haleyton', now()),
('443','South Virginiatown', now()),
('444','Caspermouth', now()),
('445','East Bernhardbury', now()),
('446','Hintzshire', now()),
('447','Lake Cielo', now()),
('448','South Clemensborough', now()),
('449','Freddyland', now()),
('450','Cortezmouth', now()),
('451','New Olaside', now()),
('452','Medaton', now()),
('453','Hayesbury', now()),
('454','Nikolausville', now()),
('455','Stellaburgh', now()),
('456','Juniorland', now()),
('457','South Courtney', now()),
('458','Karleyhaven', now()),
('459','Port Hazelhaven', now()),
('460','South Micah', now()),
('461','East Kayleigh', now()),
('462','Pfannerstillshire', now()),
('463','Rohanland', now()),
('464','Port Johnathonton', now()),
('465','Luciusberg', now()),
('466','Port Nicholasborough', now()),
('467','Anthonyfort', now()),
('468','Labadieview', now()),
('469','New Miaville', now()),
('470','Kristinchester', now()),
('471','Emersonstad', now()),
('472','Port Maryamshire', now()),
('473','South Consuelo', now()),
('474','Babyburgh', now()),
('475','Kuphalview', now()),
('476','Port Stefan', now()),
('477','Port Terrillton', now()),
('478','North Beatriceburgh', now()),
('479','Erdmanville', now()),
('480','West Kaleside', now()),
('481','Port Isacbury', now()),
('482','Port Braeden', now()),
('483','O\'Reillyville', now()),
('484','New Braxton', now()),
('485','Dennisland', now()),
('486','Candidaport', now()),
('487','Evantown', now()),
('488','Edgarchester', now()),
('489','Kuhlmanbury', now()),
('490','Ruthiebury', now()),
('491','East Colin', now()),
('492','Howelltown', now()),
('493','Naderberg', now()),
('494','Corkeryland', now()),
('495','Lake Madisyn', now()),
('496','North Carolyneland', now()),
('497','West Thaliatown', now()),
('498','New Juwan', now()),
('499','Port Perry', now()),
('500','West Alexafurt', now()),
('501','Rutherfordfort', now()),
('502','Ziemannborough', now()),
('503','Port Darius', now()),
('504','Port Kobe', now()),
('505','Barrowsland', now()),
('506','Ivyfort', now()),
('507','Garrickport', now()),
('508','Gerlachmouth', now()),
('509','Beiertown', now()),
('510','New Rowan', now()),
('511','New Rosemariemouth', now()),
('512','Laurenfurt', now()),
('513','New Dangelo', now()),
('514','Elsemouth', now()),
('515','New Rosalyntown', now()),
('516','Jacktown', now()),
('517','Port Jeffry', now()),
('518','Darianamouth', now()),
('519','New Vivaton', now()),
('520','Wisokyhaven', now()),
('521','Romaguerafurt', now()),
('522','Dietrichtown', now()),
('523','West Julien', now()),
('524','Keeblerland', now()),
('525','Ebertborough', now()),
('526','Hudsonstad', now()),
('527','Alexandreashire', now()),
('528','Nikolausshire', now()),
('529','Theresechester', now()),
('530','Theresiashire', now()),
('531','Lenoramouth', now()),
('532','Gerhardland', now()),
('533','Vestashire', now()),
('534','Lake Isai', now()),
('535','Port Daisy', now()),
('536','Marioburgh', now()),
('537','West Susanashire', now()),
('538','Goldnerstad', now()),
('539','West Elvatown', now()),
('540','Port Keyshawnchester', now()),
('541','West Valentin', now()),
('542','Crooksbury', now()),
('543','East Parker', now()),
('544','Lake Maverickstad', now()),
('545','East Bellachester', now()),
('546','Muellerton', now()),
('547','South Marcusport', now()),
('548','Lake Kittytown', now()),
('549','West Salma', now()),
('550','Lake Shirley', now()),
('551','Lake Vitoville', now()),
('552','Elizabethborough', now()),
('553','East Keegan', now()),
('554','Petermouth', now()),
('555','East Cyrushaven', now()),
('556','Flavieberg', now()),
('557','Paucekhaven', now()),
('558','Port Onabury', now()),
('559','Maximusshire', now()),
('560','New Adolfo', now()),
('561','East Nova', now()),
('562','Kalebborough', now()),
('563','Keeleyburgh', now()),
('564','New Demondmouth', now()),
('565','Lake Ana', now()),
('566','West Veronica', now()),
('567','South Monserratbury', now()),
('568','West Domenicaville', now()),
('569','Jaydetown', now()),
('570','Abernathyville', now()),
('571','Considinetown', now()),
('572','Lake Brisa', now()),
('573','New Devante', now()),
('574','Walkerton', now()),
('575','Ethanshire', now()),
('576','Weissnathaven', now()),
('577','New Lilianberg', now()),
('578','Romagueraville', now()),
('579','New Jarrettstad', now()),
('580','Adamsmouth', now()),
('581','Caleighmouth', now()),
('582','North Gerhardport', now()),
('583','Wardchester', now()),
('584','East Colt', now()),
('585','Stantonville', now()),
('586','O\'Connellview', now()),
('587','Raphaelmouth', now()),
('588','Robertshaven', now()),
('589','Aracelyland', now()),
('590','New Maurine', now()),
('591','Lake Ollie', now()),
('592','Port Adolph', now()),
('593','South Josueport', now()),
('594','Wardtown', now()),
('595','West Ezraview', now()),
('596','Kylerborough', now()),
('597','South Arno', now()),
('598','Lake Carsonmouth', now()),
('599','South Marcview', now()),
('600','Vallieside', now()),
('601','Katlynchester', now()),
('602','West Brielle', now()),
('603','Hackettfort', now()),
('604','New Clementineland', now()),
('605','D\'Amoremouth', now()),
('606','Lake Austyn', now()),
('607','Mozellebury', now()),
('608','Nicolasfurt', now()),
('609','Benjaminland', now()),
('610','Lelahmouth', now()),
('611','Schulistview', now()),
('612','West Bobbie', now()),
('613','South Mercedes', now()),
('614','Brandymouth', now()),
('615','Gutmannberg', now()),
('616','Dietrichburgh', now()),
('617','South Earlfort', now()),
('618','Beerhaven', now()),
('619','Bergstrommouth', now()),
('620','South Reggieburgh', now()),
('621','Lexiburgh', now()),
('622','New Zachariahborough', now()),
('623','Hoegermouth', now()),
('624','Monahanshire', now()),
('625','Smithberg', now()),
('626','Hyattport', now()),
('627','Volkmanburgh', now()),
('628','West Hester', now()),
('629','New Dulce', now()),
('630','Lake Dudley', now()),
('631','Lake Pricebury', now()),
('632','Johnsview', now()),
('633','Port Alexandrachester', now()),
('634','Bartellmouth', now()),
('635','Montebury', now()),
('636','Kattieport', now()),
('637','Larkintown', now()),
('638','Krisville', now()),
('639','Donavonchester', now()),
('640','North Johannaberg', now()),
('641','Collinsfurt', now()),
('642','Wolffton', now()),
('643','Verdaberg', now()),
('644','North Orrinbury', now()),
('645','East Destini', now()),
('646','Gunnerburgh', now()),
('647','East Krista', now()),
('648','Port Connor', now()),
('649','New Ernestotown', now()),
('650','Zboncakton', now()),
('651','Deangeloview', now()),
('652','West Baileyshire', now()),
('653','Missouriton', now()),
('654','North Sister', now()),
('655','Hyatthaven', now()),
('656','Ziemannhaven', now()),
('657','Modestatown', now()),
('658','Wymanport', now()),
('659','Kodyville', now()),
('660','Lake Maymieville', now()),
('661','Gaylordburgh', now()),
('662','Michelemouth', now()),
('663','Port Samara', now()),
('664','Lake Casandrabury', now()),
('665','Melodyport', now()),
('666','New Gilberto', now()),
('667','North Maida', now()),
('668','Binsview', now()),
('669','West Kylerstad', now()),
('670','East Salvadorside', now()),
('671','West Frances', now()),
('672','Lake Juniorfurt', now()),
('673','Alland', now()),
('674','Vivafurt', now()),
('675','South Ismael', now()),
('676','West Leopold', now()),
('677','West Diana', now()),
('678','West Jonatan', now()),
('679','East Sagetown', now()),
('680','Hettingerburgh', now()),
('681','Lake Ephraimmouth', now()),
('682','Shaynastad', now()),
('683','Ressieburgh', now()),
('684','Lake Ryleeville', now()),
('685','Port Jayde', now()),
('686','Kristianfort', now()),
('687','East Hailee', now()),
('688','South Abigaleside', now()),
('689','North Thora', now()),
('690','Grimestown', now()),
('691','Port Charlesshire', now()),
('692','Lake Violaburgh', now()),
('693','Port Broderickfurt', now()),
('694','South Nicholeside', now()),
('695','West Christiana', now()),
('696','West Tremouth', now()),
('697','Lake Jamaalborough', now()),
('698','Weberside', now()),
('699','South Candidaport', now()),
('700','Wintheiserhaven', now()),
('701','Deckowtown', now()),
('702','South Kelliland', now()),
('703','East Macyberg', now()),
('704','Donatohaven', now()),
('705','New Adolphbury', now()),
('706','New Rosario', now()),
('707','Kassulkebury', now()),
('708','Desmondside', now()),
('709','Powlowskiville', now()),
('710','Flatleymouth', now()),
('711','Waterschester', now()),
('712','Gottliebside', now()),
('713','Shaynaview', now()),
('714','Port Fidelfort', now()),
('715','South Lula', now()),
('716','East Audreanne', now()),
('717','East Brad', now()),
('718','Sporerberg', now()),
('719','D\'Amoretown', now()),
('720','Giabury', now()),
('721','East Elbert', now()),
('722','Jamilburgh', now()),
('723','East Mackenzieton', now()),
('724','Port Albinburgh', now()),
('725','South Irwin', now()),
('726','New Rowland', now()),
('727','Johnstonview', now()),
('728','Walterberg', now()),
('729','Berniermouth', now()),
('730','Zettachester', now()),
('731','New Garrisonland', now()),
('732','West Donaldland', now()),
('733','Lethachester', now()),
('734','Jakestad', now()),
('735','East Luciousmouth', now()),
('736','North Ola', now()),
('737','East Coltonmouth', now()),
('738','Mrazport', now()),
('739','Shanonville', now()),
('740','New Vanessaton', now()),
('741','East Zelma', now()),
('742','Lake Laurettashire', now()),
('743','Hectorfort', now()),
('744','Nolanton', now()),
('745','New Joanie', now()),
('746','New Jordane', now()),
('747','West Gideon', now()),
('748','Port Omer', now()),
('749','Xzavierborough', now()),
('750','South Gretaview', now()),
('751','South Kaycee', now()),
('752','Jackelineberg', now()),
('753','West Mortimer', now()),
('754','East Rubye', now()),
('755','Lake Ruben', now()),
('756','Corbinmouth', now()),
('757','Schuppeside', now()),
('758','East Janie', now()),
('759','Gutmannmouth', now()),
('760','Tremblaystad', now()),
('761','Luraport', now()),
('762','Farrellview', now()),
('763','West Noeliatown', now()),
('764','Goldatown', now()),
('765','Dooleyview', now()),
('766','Lake Patsy', now()),
('767','Chloeborough', now()),
('768','Mayerland', now()),
('769','Ferrymouth', now()),
('770','Yundtborough', now()),
('771','Handton', now()),
('772','Parkerfort', now()),
('773','New Ceasarport', now()),
('774','West Nadia', now()),
('775','Lake Grady', now()),
('776','East Rachelle', now()),
('777','New Isabel', now()),
('778','New Rozellafort', now()),
('779','Schaeferport', now()),
('780','East Shanon', now()),
('781','Port Chaya', now()),
('782','North Mina', now()),
('783','Kerlukeport', now()),
('784','Port Isomside', now()),
('785','Lake Oranborough', now()),
('786','Lake Alexandrachester', now()),
('787','Port Ali', now()),
('788','Ciarastad', now()),
('789','West Camyllestad', now()),
('790','Kemmerhaven', now()),
('791','Krystinahaven', now()),
('792','Abernathytown', now()),
('793','O\'Connellport', now()),
('794','Johnathonton', now()),
('795','Madalynberg', now()),
('796','Langshire', now()),
('797','North Robertahaven', now()),
('798','Morrisburgh', now()),
('799','Jacobschester', now()),
('800','Demetrischester', now()),
('801','Rennerborough', now()),
('802','Dejahland', now()),
('803','East Elyssaview', now()),
('804','South Baileeview', now()),
('805','North Judgeland', now()),
('806','East Warren', now()),
('807','Gerholdmouth', now()),
('808','Asaberg', now()),
('809','Marcelofurt', now()),
('810','Timmothyview', now()),
('811','Goyetteport', now()),
('812','East Cale', now()),
('813','South Coty', now()),
('814','Lake Ivorystad', now()),
('815','Nameside', now()),
('816','Port Osvaldoland', now()),
('817','Mertzton', now()),
('818','South Celia', now()),
('819','East Archberg', now()),
('820','Zenamouth', now()),
('821','Lake Abbieside', now()),
('822','East Alessandrahaven', now()),
('823','Lake Julianview', now()),
('824','West Jaylonmouth', now()),
('825','Port Elenoraberg', now()),
('826','Langmouth', now()),
('827','North Zackview', now()),
('828','North Thaliaton', now()),
('829','Benjaminstad', now()),
('830','Halvorsonmouth', now()),
('831','Port Agustin', now()),
('832','North Katlynn', now()),
('833','Kovacekburgh', now()),
('834','South Matildaborough', now()),
('835','North Gerry', now()),
('836','Lockmanport', now()),
('837','Lake Loycehaven', now()),
('838','Darrelton', now()),
('839','North Elainaburgh', now()),
('840','Port Deontae', now()),
('841','Boganmouth', now()),
('842','Luluside', now()),
('843','East Lilla', now()),
('844','Jorgeland', now()),
('845','Bergnaumbury', now()),
('846','Port Anikaside', now()),
('847','Fisherfurt', now()),
('848','Lake Morton', now()),
('849','West Lisandro', now()),
('850','New Loytown', now()),
('851','New Ruben', now()),
('852','Bartholomemouth', now()),
('853','Millermouth', now()),
('854','New Jedville', now()),
('855','Lake Waino', now()),
('856','Aureliahaven', now()),
('857','New Rosetta', now()),
('858','Baileeton', now()),
('859','Patriciashire', now()),
('860','Leslieburgh', now()),
('861','Konopelskiport', now()),
('862','East Pierreport', now()),
('863','South Gerdafurt', now()),
('864','North Aurelia', now()),
('865','New Alliestad', now()),
('866','West Ramon', now()),
('867','South Kayleigh', now()),
('868','Reidchester', now()),
('869','Rachelborough', now()),
('870','Schulisttown', now()),
('871','Bechtelarborough', now()),
('872','Roseshire', now()),
('873','Port Arnofurt', now()),
('874','North Sonyaport', now()),
('875','Hackettside', now()),
('876','New Lolitaville', now()),
('877','Starkbury', now()),
('878','Roobburgh', now()),
('879','Lake Precious', now()),
('880','Jastbury', now()),
('881','South Juvenal', now()),
('882','Manteside', now()),
('883','New Pollyfurt', now()),
('884','Cristophermouth', now()),
('885','Imaniside', now()),
('886','Cartwrightton', now()),
('887','North Jose', now()),
('888','Jensenstad', now()),
('889','Lorineville', now()),
('890','Manteshire', now()),
('891','New Leonborough', now()),
('892','North Deshawnhaven', now()),
('893','East Francis', now()),
('894','Burniceburgh', now()),
('895','New Mariahville', now()),
('896','Bahringertown', now()),
('897','Hauckstad', now()),
('898','Port Danial', now()),
('899','South Kaleighborough', now()),
('900','Gradyburgh', now()),
('901','Jerdehaven', now()),
('902','Feestton', now()),
('903','East Dorthy', now()),
('904','East Donnyport', now()),
('905','Handstad', now()),
('906','New Stephanychester', now()),
('907','Bernicebury', now()),
('908','Franeckiland', now()),
('909','Lake Paulmouth', now()),
('910','West Carolineborough', now()),
('911','East Raoulhaven', now()),
('912','North Stephania', now()),
('913','Howellborough', now()),
('914','West Cobyville', now()),
('915','Cloydmouth', now()),
('916','Port Oscar', now()),
('917','Sporerchester', now()),
('918','Nitzscheville', now()),
('919','West Tiannashire', now()),
('920','Walshport', now()),
('921','East Rhiannaberg', now()),
('922','Lake Gay', now()),
('923','Murazikshire', now()),
('924','Pollichview', now()),
('925','Carolinetown', now()),
('926','South Ashleigh', now()),
('927','West Maegantown', now()),
('928','Dejonville', now()),
('929','Port Dortha', now()),
('930','South Jaylen', now()),
('931','Geraldineland', now()),
('932','Parkerhaven', now()),
('933','Halvorsonstad', now()),
('934','Alexandraview', now()),
('935','Port Brettbury', now()),
('936','Bodeport', now()),
('937','Lake Hopehaven', now()),
('938','New Claudinetown', now()),
('939','West Annabelletown', now()),
('940','Shanellefurt', now()),
('941','Cartwrightside', now()),
('942','West Kameronborough', now()),
('943','Yundtfurt', now()),
('944','Willaborough', now()),
('945','West Alizaberg', now()),
('946','Barrowsbury', now()),
('947','Sonyaland', now()),
('948','Kendraburgh', now()),
('949','Auerside', now()),
('950','East Opalbury', now()),
('951','Lake Dock', now()),
('952','Nikoport', now()),
('953','Balistrerishire', now()),
('954','North Nick', now()),
('955','Port Candidafurt', now()),
('956','Selenaside', now()),
('957','West Laishaville', now()),
('958','Abshirehaven', now()),
('959','West Meggiebury', now()),
('960','Lake Alf', now()),
('961','West Bernhard', now()),
('962','East Waylon', now()),
('963','Port Eloisa', now()),
('964','West Lucie', now()),
('965','Oletaton', now()),
('966','North Evangelineburgh', now()),
('967','Port Jarrett', now()),
('968','Port Daisha', now()),
('969','Haleytown', now()),
('970','Zulauffort', now()),
('971','Howestad', now()),
('972','Stephaniastad', now()),
('973','West Vladimirfurt', now()),
('974','New Eileen', now()),
('975','North Luis', now()),
('976','West Stevieborough', now()),
('977','North Magnolia', now()),
('978','Tracyburgh', now()),
('979','North Eulastad', now()),
('980','Borerburgh', now()),
('981','North Nils', now()),
('982','Lake Enoch', now()),
('983','South Fionamouth', now()),
('984','Hartmannview', now()),
('985','Albertburgh', now()),
('986','Leschview', now()),
('987','Kshlerinmouth', now()),
('988','South Tristinmouth', now()),
('989','Sauerport', now()),
('990','Jastside', now()),
('991','Legrosberg', now()),
('992','West Harveybury', now()),
('993','South Mathilde', now()),
('994','Shemarfort', now()),
('995','East Leannport', now()),
('996','Port Willardborough', now()),
('997','Vonview', now()),
('998','Herzogmouth', now()),
('999','Lake Kadinborough', now()),
('1000','North Dorris',now());";

if (mysqli_query($conn, $sql)) { 
    echo "New record created successfully"; 
} else { 
    echo "Error: " . $sql . "<br>" . mysqli_error($conn); 
}

// Close coneection 
mysqli_close($conn); 
?>